# Generated by Django 4.1.5 on 2023-01-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_descriptiontocategorymapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
