# Generated by Django 4.1.5 on 2023-03-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_unique_activity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='activity',
            name='unique_activity',
        ),
    ]
