[tool.pyright]
include = ["lambdas/AuthLayer"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "**/.pytype",
    "src/typestubs"

]
# ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }
# stubPath = "src/stubs"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.11"
# pythonPlatform = "Linux"
pythonPath = "."

extraPaths =  [ "lambdas/AuthLayer", "lambdas/activities"]

executionEnvironments = [
#  { root = "src/web", pythonVersion = "3.5", pythonPlatform = "Windows", extraPaths = [ "src/service_libs" ] },
#  { root = "src/sdk", pythonVersion = "3.0", extraPaths = [ "src/backend" ] },
#  { root = "src/tests", extraPaths = ["src/tests/e2e", "src/sdk" ]},
  { root = "lambdas" }
]
