# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "backendLambdasSamDev"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.validate]
[default.validate.parameters]
lint = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "backendLambdasSamDev"
s3_prefix = "backendLambdasSam/dev"
region = "us-east-1"
disable_rollback = true
image_repositories = []
parameter_overrides = "BranchPrefix=dev"

[default.package]
[default.package.parameters]
resolve_s3 = true

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod]
[prod.global]
[prod.global.parameters]
stack_name="backendLambdasSam"

[prod.deploy]
[prod.deploy.parameters]
resolve_s3 = true
stack_name = "backendLambdasSam"
s3_prefix="backendLambdasSam"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
region = "us-east-1"
parameter_overrides = "BranchPrefix='prod' ApiStageName=Prod"


[test]
[test.global]
[test.global.parameters]
stack_name="backendLambdasSamDev"

[test.sync]
[test.sync.parameters]
watch = true
parameter_overrides = "SkipAuth='1'"
