AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend_lambdas_sam

  Sample SAM Template for backend_lambdas_sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 640
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  # api gateway
  FinanceAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Test
      AccessLogSettings:
        DestinationArn: !GetAtt ApiLogs.Arn
        Format: >-
          {"requestId": "$context.requestId", "error": "$context.authorizer.error" }
      Auth:
        Authorizers:
          MyLambdaTokenAuthorizer:
            AuthorizerPayloadFormatVersion: 1.0
            FunctionInvokeRole:
              Fn::GetAtt:
                - MyAuthRole
                - Arn
            FunctionArn:
              Fn::GetAtt:
                - MyAuthFunction
                - Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0
          OAuthAuthorizer:
            JwtConfiguration:
              issuer: "https://dev-55m1hzkqt35ta6tx.us.auth0.com/"
              audience:
                - https://fbbvgusi51.execute-api.us-east-1.amazonaws.com
            IdentitySource: "$request.header.Authorization"
      CorsConfiguration:
        AllowMethods: 
          - OPTIONS
          - POST
          - GET
          - DELETE
        AllowHeaders: 
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowOrigins:
          - "http://localhost:3000"
          - "https://fantadrinker.github.io"
        MaxAge: 600

  ApiLogs:
    Type: AWS::Logs::LogGroup

  # lambda functions
  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/financeAuthorizer/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          BASE_URL: "https://dev-55m1hzkqt35ta6tx.us.auth0.com"
  
  # required permissions
  MyAuthRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: "InvokeMyAuthFunction"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                Resource: !GetAtt MyAuthFunction.Arn

  MultiplyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/multiply/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        Multiply:
          Type: HttpApi 
          Properties:
            ApiId:
              Ref: FinanceAPI
            Path: /multiply
            Method: GET
            Auth:
              Authorizer: OAuthAuthorizer
  ActivitiesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/activities/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable
      Architectures:
      - x86_64
      Environment:
        Variables:
          ACTIVITIES_TABLE: !Ref ActivitiesTable
          BASE_URL: "https://dev-55m1hzkqt35ta6tx.us.auth0.com"
      Events:
        PostActivities:
          Type: HttpApi 
          Properties:
            ApiId:
              Ref: FinanceAPI
            Path: /activities
            Method: POST
        GetActivities:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: FinanceAPI
            Path: /activities
            Method: GET
        DeleteActivities:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: FinanceAPI
            Path: /activities
            Method: DELETE
  FileCheckFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/fileCheck/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable
      Architectures:
      - x86_64
      Environment:
        Variables:
          ACTIVITIES_TABLE: !Ref ActivitiesTable
          BASE_URL: "https://dev-55m1hzkqt35ta6tx.us.auth0.com"
      Events:
        GetFileChecks:
          Type: HttpApi 
          Properties:
            ApiId:
              Ref: FinanceAPI
            Path: /chksums
            Method: GET
  ActivityInsightsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/activityInsights/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable
      Architectures:
      - x86_64
      Environment:
        Variables:
          ACTIVITIES_TABLE: !Ref ActivitiesTable
          BASE_URL: "https://dev-55m1hzkqt35ta6tx.us.auth0.com"
      Events:
        GetInsights:
          Type: HttpApi 
          Properties:
            ApiId:
              Ref: FinanceAPI
            Path: /insights
            Method: GET
        
  MappingsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambdas/mappings/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable
      Architectures:
      - x86_64
      Environment:
        Variables:
          ACTIVITIES_TABLE: !Ref ActivitiesTable
          BASE_URL: "https://dev-55m1hzkqt35ta6tx.us.auth0.com"
      Events:
        GetMappings:
          Type: HttpApi 
          Properties:
            ApiId:
              Ref: FinanceAPI
            Path: /mappings
            Method: GET
        PostMappings:
          Type: HttpApi 
          Properties:
            ApiId:
              Ref: FinanceAPI
            Path: /mappings
            Method: POST
        DeleteMappings:
          Type: HttpApi 
          Properties:
            ApiId:
              Ref: FinanceAPI
            Path: /mappings
            Method: DELETE

  ActivitiesTableStreamProcessor:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdas/activitiesStreams/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable
        - DynamoDBStreamReadPolicy:
            TableName: !Ref ActivitiesTable
            StreamName: !GetAtt ActivitiesTable.StreamArn
      Architectures:
      - x86_64
      Environment:
        Variables:
          ACTIVITIES_TABLE: !Ref ActivitiesTable
      Events:
        ProcessNewActivitiesOrMappings:
          Type: DynamoDB
          Properties:
            Stream: 
              !GetAtt ActivitiesTable.StreamArn
            StartingPosition: TRIM_HORIZON
            FilterCriteria:
              Filters:
                - Pattern: '{"dynamodb": {"Keys": {"sk": {"S": [{"prefix": "20"}, {"prefix": "mapping#"}]}}}}'
  
  MonthlyCheckFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambdas/monthlyCheck/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable
      Architectures:
      - x86_64
      Environment:
        Variables:
          ACTIVITIES_TABLE: !Ref ActivitiesTable

  # dynamodb tables
  ActivitiesTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - AttributeName: user
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: user
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MultiplyApi:
    Description: API Gateway endpoint URL for Prod stage for Multiply function
    Value: !Sub "https://${FinanceAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/multiply/"
  MultiplyFunction:
    Description: Multiply Lambda Function ARN
    Value: !GetAtt MultiplyFunction.Arn
  MultiplyFunctionIamRole:
    Description: Implicit IAM Role created for Multiply function
    Value: !GetAtt MultiplyFunctionRole.Arn
