AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend_lambdas_sam

  Sample SAM Template for backend_lambdas_sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  # api gateway
  FinanceAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Test
      Auth:
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt MyAuthFunction.Arn
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'http://localhost:3000'"
        AllowCredentials: true
        MaxAge: "'600'"

  # lambda functions
  MyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: financeAuthorizer/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Environment:
        Variables:
          BASE_URL: "https://dev-55m1hzkqt35ta6tx.us.auth0.com"
  
  # required permissions
  MyAuthPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MyAuthFunction.Arn
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FinanceAPI}/authorizers/${MyAuthFunction}"
    

  MultiplyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: multiply/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        Multiply:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref FinanceAPI
            Path: /multiply
            Method: get
            Auth:
              Authorizer: MyLambdaTokenAuthorizer
  ActivitiesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: activities/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ActivitiesTable
      Architectures:
      - x86_64
      Environment:
        Variables:
          ACTIVITIES_TABLE: !Ref ActivitiesTable
      Timeout: 7
      Events:
        Activities:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref FinanceAPI
            Path: /activities
            Method: post
            Auth:
              Authorizer: MyLambdaTokenAuthorizer
  # dynamodb tables
  ActivitiesTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MultiplyApi:
    Description: API Gateway endpoint URL for Prod stage for Multiply function
    Value: !Sub "https://${FinanceAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/multiply/"
  MultiplyFunction:
    Description: Multiply Lambda Function ARN
    Value: !GetAtt MultiplyFunction.Arn
  MultiplyFunctionIamRole:
    Description: Implicit IAM Role created for Multiply function
    Value: !GetAtt MultiplyFunctionRole.Arn
