# workflow for testing builds for PRs
name: Check if PR can be built successfully

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["*"]


permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash
    working-directory: ./frontend
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: './frontend/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: run test
        run: npx jest
      - name: Build static html
        run: PUBLIC_URL=https://fantadrinker.github.io/finance-app/ node scripts/build.js
