# workflow for testing builds for PRs
name: Check if PR can be built successfully in backend

on:
  # Runs on pushes targeting the default branch
  push:
    branches-ignore:
      - main
    paths-ignore:
      - frontend/** # this will be fixed when the directory name is changed


permissions:
    contents: read
    id-token: write

defaults:
    run:
        shell: bash
        working-directory: ./backend_lambdas_sam

jobs:
    build-and-test-backend:
        environment: aws-prod
        runs-on: ubuntu-latest
        strategy:
            matrix:
              python-version: ["3.9"]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Echo environemnts
              run: env
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install ruff pytest
                  if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
            - name: run unit tests
              run: pytest tests/unit -v -rP
            - uses: aws-actions/setup-sam@v2
              with:
                  use-installer: true
            - uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: build backend
              run: sam build --use-container
            - name: deploy to test stack
              run: sam deploy --config-env=test --no-confirm-changeset --no-fail-on-empty-changeset
            - name: run integration tests
              run: pytest tests/integration -v -rP
            - name: clean up and teardown test stack
              run: python scripts/delete_files.py && sam delete --config-env=test --no-prompts
