name: "Verify and deploys sam"

on:
  pull_request:

defaults:
    run:
        shell: bash
        working-directory: ./backend_lambdas_sam

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: get-changeset
        run: | 
          sam deploy --no-execute-changeset | sed -n '/CloudFormation stack changeset/, /Changeset created successfully/p' > tmp.txt
      - name: post-comment
        run: |
          # Use GitHub API to create a comment on the PR
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT=$(cat tmp.txt)
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"
