name: "Verify and deploys sam"

on:
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ./backend_lambdas_sam

jobs:
  auto-comment:
    runs-on: ubuntu-latest
    environment: aws-prod
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: get-changeset
        run: | 
          sam deploy --no-execute-changeset | sed -n '/CloudFormation stack changeset/, /Changeset created successfully/p' > tmp.txt
      - name: post-comment
        run: |
          # Use GitHub API to create a comment on the PR
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT=$(jq -Rs '.' tmp.txt)
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"

      - name: debug
        run: echo "{\"body\":\"$COMMENT\"}"
