# workflow for testing builds for PRs
name: build and deploy lambdas and apis to SAM in AWS

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash
    working-directory: ./backend_lambdas_sam
  
jobs:
  setup-build-env:
    runs-on: ubuntu-latest
    environment: aws-prod
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Build inside Docker containers
      - run: sam build --use-container
      # Prevent prompts and failure when the stack is unchanged
      # sadly this would not work, fails with 
      # Error: Cannot use both --resolve-s3 and --s3-bucket parameters in non-guided deployments. Please use only one or use the --guided option for a guided deployment.
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env=prod